export default
[{
    "cc":	"Coordinating conjunction",
    "cd":	"Cardinal number",
    "dt":	"Determiner",
    "ex":	"Existential there",
    "fw":	"Foreign word",
    "in":	"Preposition",
    "jj":	"Adjective",
    "a":	"Adjective",
    "ls":	"List item marker",
    "md":	"Modal",
    "nn":	"Noun",
    "nns":	"Noun, plural",
    "nnp":	"Proper noun",
    "nnps":	"Proper noun",
    "pdt":	"Predeterminer",
    "pos":	"Possessive ending",
    "prp":	"Personal pronoun",
    "prp$":	"Possessive pronoun",
    "rb":	"Adverb",
    "rbr":	"Adverb",
    "rbs":	"Adverb",
    "rp":	"Particle",
    "sym":	"Symbol",
    "to":	"to",
    "uh":	"Interjection",
    "v":	"Verb",
    "vbd":	"Verb, past tense",
    "wdt":	"Determiner",
    "wp$:	"Possessive pronoun",
}]
