export default [
    "aluminium foil",
    "bopet",
    "bubble wrap",
    "cellophane",
    "corrugated fiberboard",
    "corrugated plastic",
    "cushioning",
    "foam peanut",
    "glass",
    "hot-melt adhesive",
    "kraft paper",
    "linear low-density polyethylene",
    "liquid packaging board",
    "low-density polyethylene",
    "metallised film",
    "modified atmosphere",
    "molded pulp",
    "nonwoven fabric",
    "paperboard",
    "plastic film",
    "plastic wrap",
    "polyester",
    "polyethylene",
    "polypropylene",
    "shrinkwrap",
    "tinplate",
    "velostat",
    "aluminium",
    "chromium",
    "copper",
    "gold",
    "iron",
    "lead",
    "nickel",
    "platinum",
    "silver",
    "tin",
    "titanium",
    "zinc",
    "steel",
    "brass",
    "electrum",
    "bronze",
    "sterling",
    "pewter",

]